language: python
python:
  - "2.6"
  - "2.7"
env:
  matrix:
    - ES_VERSION=1.0.0
    - ES_VERSION=1.0.1
    - ES_VERSION=1.0.2
    - ES_VERSION=1.0.3
    - ES_VERSION=1.1.0
    - ES_VERSION=1.1.1
before_install:
  - 'wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.deb -O elasticsearch.deb'
  - 'sudo dpkg -i elasticsearch.deb'
  - 'sudo service elasticsearch start'
install: "pip install -r development.txt --use-mirrors"
script:
  - make
after_success:
  - coveralls